CXX=mingw32-g++
INCLUDEDIR=include
SOURCEFILES=src\main.cpp src\bitmap.cpp src\idgenerator.cpp
OBJFILES=$(SOURCEFILES:.cpp=.o ) 




XXXXX: $(OBJFILES)
	$(CXX) $(OBJFILES) -o XXXXX.exe

$(OBJFILES):  $(SOURCEFILES)

.cpp.o:
	$(CXX) -I $(INCLUDEDIR) -c $< -o $@

	
clean:
	del $(OBJFILES) 
	del XXXXX.exe